replicaCount: 1
username: "sonar"
password: "CHANGEME" 
image:
  repository: "sonarqube"
  tag: "6.7"
  pullPolicy: Always
  pullSecret: "github"

securityContext:
  fsGroup: 999
  runAsUser: 999
  runAsGroup: 999
scc:
  create: false

serviceAccount:
  create: true
  name: sonarsa

service:
  name: sonarqube
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000
  labels:
  annotations: {}
  loadBalancerSourceRanges:
  - 0.0.0.0/0

route:
  enabled: false
  labels: {}
  annotations: {}
  path: "sonarqube.apps.cluster.sss.local"


ingress:
  enabled: true
  hosts:
    - name: sonar.sdp.com
      path: /
      # path: /sonarqube
  annotations: {}
  tls: []

affinity: {}

tolerations: []

nodeSelector: {}

hostAliases: []

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  sonarWebContext: /

extraEnv: {}

annotations: {}

resources: {}
persistence:
  enabled: false
  annotations: {}

plugins:
  install: 
     - "https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.1.0.13090.jar"
     - "https://github.com/SonarQubeCommunity/sonar-pmd/releases/download/2.6/sonar-pmd-plugin-2.6.jar"
     - "https://github.com/checkstyle/sonar-checkstyle/releases/download/4.8/checkstyle-sonar-plugin-4.8.jar"
     - "https://github.com/spotbugs/sonar-findbugs/releases/download/3.6.0/sonar-findbugs-plugin-3.6.0.jar"
     - "https://binaries.sonarsource.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-4.0.0.5862.jar"

  resources: {}
sonarproperties:
  sonar.jdbc.url: "jdbc:postgresql://localhost/sonar"
  sonar.ce.javaOpts: "-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError"
  sonar.search.javaOpts: "-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError"
  sonar.web.javaOpts: "-Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError"
  sonar.forceAuthentication: "${env:FORCE_AUTHENTICATION}"

database:
  type: "postgresql"

postgresql:
  enabled: true
  postgresUser: "CHANGEME"
  postgresPassword: "CHANGEME"
  postgresDatabase: "CHANGEME"
  service:
    port: 5432

podLabels: {}
