site:
  title: Solutions Delivery Platform
  url: http://localhost
  start_page: deployment-guides::index.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: deployment-guides
ui: 
  bundle: 
    url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.1/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
